name: "godot-ci export"
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#  push:
#    branches: [ main ]
#  pull_request:
#    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



env:
  GODOT_VERSION: 3.2.3
  EXPORT_NAME: crash

jobs:
  export-windows:
    name: Windows Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p build/linux build/windows build/mac build/web ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Windows Build
        run: godot -v --export "Windows Desktop" ./build/windows/$EXPORT_NAME.exe
      - name: Windows Release
        uses: ridedott/release-me-action@master
        with:
          release-assets: ./build/windows/$EXPORT_NAME.exe
          dry-run: true

  export-linux:
    name: Linux Export
    runs-on: ubuntu-latest
    container:
      image: docker://barichello/godot-ci:3.2.3
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Setup
        run: |
          mkdir -v -p build/linux build/windows build/mac build/web ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable
      - name: Linux Build
        run: godot -v --export "Linux/X11" ./build/linux/$EXPORT_NAME.x86_64
      - name: Linux Release Release
        uses: ridedott/release-me-action@master
        with:
          release-assets: ./build/linux/$EXPORT_NAME.x86_64
          dry-run: true